jobs:
- template: matrix.yml
  parameters:
    windowsPoolName: NetCoreInternal-Pool
    windowsQueueName: buildpool.windows.10.amd64.vs2017

- template: ../jobs/collect-artifacts.yml
  parameters:
    dependsOn:
      - centos71
      - debian9
      - fedora30
      - ubuntu1804
    pool:
      vmImage: vs2017-win2016

- template: /eng/common/templates/job/publish-build-assets.yml
  parameters:
    dependsOn:
      - Collect_Artifacts
    enablePublishBuildArtifacts: true
    pool:
      vmImage: vs2017-win2016
